// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Knex } from "knex";

declare module "knex/types/tables" {
  export interface Tables {
    glpi_tickets: {
      id: number;
      entities_id: number;
      name: string;
      date: string;
      closedate: string | null;
      solvedate: string | null;
      date_mod: string;
      users_id_lastupdater: number;
      status: number;
      users_id_recipient: number;
      requesttypes_id: number;
      content: string;
      urgency: number;
      impact: number;
      priority: number;
      itilcategories_id: number;
      type: number;
      global_validation: number;
      slas_id_ttr: number;
      slas_id_tto: number;
      slalevels_id_ttr: number;
      time_to_resolve: string | null;
      time_to_own: string | null;
      begin_waiting_date: string | null;
      sla_waiting_duration: number;
      ola_waiting_duration: number;
      olas_id_tto: number;
      olas_id_ttr: number;
      olalevels_id_ttr: number;
      ola_ttr_begin_date: string | null;
      internal_time_to_resolve: string | null;
      internal_time_to_own: string | null;
      waiting_duration: number;
      close_delay_stat: number;
      solve_delay_stat: number;
      takeintoaccount_delay_stat: number;
      actiontime: number;
      is_deleted: number;
      locations_id: number;
      validation_percent: number;
      date_creation: string;
    };

    glpi_users: {
      id: number;
      name: string;
      password: string;
      password_last_update: string | null;
      phone: string | null;
      phone2: string | null;
      mobile: string | null;
      realname: string;
      firstname: string;
      locations_id: number;
      language: string | null;
      use_mode: number;
      list_limit: number | null;
      is_active: number;
      comment: string | null;
      auths_id: number;
      authtype: number;
      last_login: string | null;
      date_mod: string;
      date_sync: string | null;
      is_deleted: number;
      profiles_id: number;
      entities_id: number;
      usertitles_id: number;
      usercategories_id: number;
      date_format: number | null;
      number_format: number | null;
      names_format: number | null;
      csv_delimiter: string;
      is_ids_visible: number | null;
      use_flat_dropdowntree: number | null;
      show_jobs_at_login: number | null;
      priority_1: string | null;
      priority_2: string | null;
      priority_3: string | null;
      priority_4: string | null;
      priority_5: string | null;
      priority_6: string | null;
      followup_private: number | null;
      task_private: number | null;
      default_requesttypes_id: number | null;
      password_forget_token: string | null;
      password_forget_token_date: string | null;
      user_dn: string | null;
      registration_number: string | null;
      show_count_on_tabs: number | null;
      refresh_views: number | null;
      set_default_tech: number | null;
      personal_token: string | null;
      personal_token_date: string | null;
      api_token: string | null;
      api_token_date: string | null;
      cookie_token: string | null;
      cookie_token_date: string | null;
      display_count_on_home: number | null;
      notification_to_myself: number | null;
      duedateok_color: string | null;
      duedatewarning_color: string | null;
      duedatecritical_color: string | null;
      duedatewarning_less: number | null;
      duedatecritical_less: number | null;
      duedatewarning_unit: string | null;
      duedatecritical_unit: string | null;
      display_options: string | null;
      is_deleted_ldap: number;
      pdffont: string | null;
      picture: string | null;
      begin_date: string | null;
      end_date: string | null;
      keep_devices_when_purging_item: number | null;
      privatebookmarkorder: string | null;
      backcreated: number | null;
      task_state: number | null;
      palette: string | null;
      page_layout: string | null;
      fold_menu: number | null;
      fold_search: number | null;
      savedsearches_pinned: string | null;
      timeline_order: string | null;
      itil_layout: string | null;
      richtext_layout: string | null;
      set_default_requester: number | null;
      lock_autolock_mode: number | null;
      lock_directunlock_notification: number | null;
      date_creation: string;
      highcontrast_css: number;
      plannings: string | null;
      sync_field: string | null;
      groups_id: number;
      users_id_supervisor: number;
      timezone: string | null;
      default_dashboard_central: string | null;
      default_dashboard_assets: string | null;
      default_dashboard_helpdesk: string | null;
      default_dashboard_mini_ticket: string | null;
      default_central_tab: number | null;
      nickname: string | null;
    };

    glpi_itilcategories: {
      id: number;
      entities_id: number;
      is_recursive: number;
      itilcategories_id: number;
      name: string;
      completename: string;
      comment: string | null;
      level: number;
      knowbaseitemcategories_id: number;
      users_id: number;
      groups_id: number;
      code: string | null;
      ancestors_cache: string | null;
      sons_cache: string | null;
      is_helpdeskvisible: number;
      tickettemplates_id_incident: number;
      tickettemplates_id_demand: number;
      changetemplates_id: number;
      problemtemplates_id: number;
      is_incident: number;
      is_request: number;
      is_problem: number;
      is_change: number;
      date_mod: string;
      date_creation: string;
    };

    glpi_locations: {
      id: number;
      entities_id: number;
      is_recursive: number;
      name: string;
      locations_id: number;
      completename: string;
      comment: string | null;
      level: number;
      ancestors_cache: string | null;
      sons_cache: string | null;
      address: string | null;
      postcode: string | null;
      town: string | null;
      state: string | null;
      country: string | null;
      building: string | null;
      room: string | null;
      latitude: string | null;
      longitude: string | null;
      altitude: string | null;
      date_mod: string;
      date_creation: string;
    };

    glpi_tickets_users: {
      id: number;
      tickets_id: number;
      users_id: number;
      type: number;
      use_notification: number;
      alternative_email: string | null;
    };

    glpi_entities: {
      id: number;
      name: string;
      entities_id: number;
      completename: string;
      comment: string | null;
      level: number;
      sons_cache: string | null;
      ancestors_cache: string | null;
      registration_number: string | null;
      address: string | null;
      postcode: string | null;
      town: string | null;
      state: string | null;
      country: string | null;
      website: string | null;
      phonenumber: string | null;
      fax: string | null;
      email: string | null;
      admin_email: string | null;
      admin_email_name: string | null;
      replyto_email: string | null;
      replyto_email_name: string | null;
      notification_subject_tag: string | null;
      ldap_dn: string | null;
      tag: string | null;
      authldaps_id: number;
      mail_domain: string | null;
      entity_ldapfilter: string | null;
      mailing_signature: string | null;
      cartridges_alert_repeat: number;
      consumables_alert_repeat: number;
      use_licenses_alert: number;
      send_licenses_alert_before_delay: number;
      use_certificates_alert: number;
      send_certificates_alert_before_delay: number;
      certificates_alert_repeat_interval: number;
      use_contracts_alert: number;
      send_contracts_alert_before_delay: number;
      use_infocoms_alert: number;
      send_infocoms_alert_before_delay: number;
      use_reservations_alert: number;
      use_domains_alert: number;
      send_domains_alert_close_expiries_delay: number;
      send_domains_alert_expired_delay: number;
      autoclose_delay: number;
      autopurge_delay: number;
      notclosed_delay: number;
      calendars_id: number;
      auto_assign_mode: number;
      tickettype: number;
      max_closedate: string | null;
      inquest_config: number;
      inquest_rate: number;
      inquest_delay: number;
      inquest_URL: string | null;
      autofill_warranty_date: string | null;
      autofill_use_date: string | null;
      autofill_buy_date: string | null;
      autofill_delivery_date: string | null;
      autofill_order_date: string | null;
      tickettemplates_id: number;
      changetemplates_id: number;
      problemtemplates_id: number;
      entities_id_software: number;
      default_contract_alert: number;
      default_infocom_alert: number;
      default_cartridges_alarm_threshold: number;
      default_consumables_alarm_threshold: number;
      delay_send_emails: number;
      is_notif_enable_default: number;
      inquest_duration: number;
      date_mod: string;
      date_creation: string;
      autofill_decommission_date: string | null;
      suppliers_as_private: number;
      anonymize_support_agents: number;
      contracts_id_default: number;
      display_users_initials: number;
      enable_custom_css: number;
      custom_css_code: string | null;
      latitude: string | null;
      longitude: string | null;
      altitude: string | null;
      calendars_strategy: number;
      changetemplates_strategy: number;
      contracts_strategy_default: number;
      entities_strategy_software: number;
      problemtemplates_strategy: number;
      tickettemplates_strategy: number;
      transfers_strategy: number;
      from_email: string | null;
      from_email_name: string | null;
      noreply_email: string | null;
      noreply_email_name: string | null;
      transfers_id: number;
      agent_base_url: string | null;
    };

    glpi_tickettasks: {
      id: number;
      tickets_id: number;
      taskcategories_id: number;
      date: string;
      begin: string | null;
      end: string | null;
      users_id: number;
      users_id_tech: number;
      content: string;
      actiontime: number;
      state: number;
      users_id_editor: number;
      date_mod: string;
      date_creation: string;
      tasktemplates_id: number;
      timeline_position: number;
      is_private: number;
    };

    glpi_itilfollowups: {
      id: number;
      itemtype: string;
      items_id: number;
      date: string;
      users_id: number;
      users_id_editor: number;
      content: string;
      is_private: number;
      requesttypes_id: number;
      date_mod: string;
      date_creation: string;
      timeline_position: number;
      sourceitems_id: number;
      sourceof_items_id: number;
    };

    glpi_itilsolutions: {
      id: number;
      itemtype: string;
      items_id: number;
      solutiontypes_id: number;
      solutiontemplates_id: number;
      content: string;
      date_creation: string;
      date_mod: string;
      date_approval: string | null;
      users_id: number;
      users_id_editor: number;
      users_id_approval: number;
      status: number;
      itilfollowups_id: number;
    };

    glpi_groups: {
      id: number;
      entities_id: number;
      is_recursive: number;
      name: string;
      comment: string | null;
      ldap_field: string | null;
      ldap_value: string | null;
      ldap_group_dn: string | null;
      date_mod: string;
      users_id: number;
      is_manager: number;
      is_userdelegate: number;
      is_notify: number;
      is_itemgroup: number;
      is_usergroup: number;
      is_assign: number;
      is_task: number;
      is_request: number;
      is_incident: number;
      is_problem: number;
      is_change: number;
      groups_id: number;
      completename: string;
      level: number;
      ancestors_cache: string | null;
      sons_cache: string | null;
      date_creation: string;
    };

    glpi_groups_tickets: {
      id: number;
      tickets_id: number;
      groups_id: number;
      type: number;
    };

    glpi_groups_users: {
      id: number;
      users_id: number;
      groups_id: number;
      is_dynamic: number;
      is_manager: number;
      is_userdelegate: number;
    };

    glpi_profiles: {
      id: number;
      name: string;
      interface: string;
      is_default: number;
      helpdesk_hardware: number;
      helpdesk_item_type: string | null;
      ticket_status: string | null;
      comment: string | null;
      problem_status: string | null;
      create_ticket_on_login: number;
      tickettemplates_id: number;
      changetemplates_id: number;
      problemtemplates_id: number;
      change_status: string | null;
      managed_domainrecordtypes: string | null;
      date_mod: string;
      date_creation: string;
    };

    glpi_slas: {
      id: number;
      name: string;
      entities_id: number;
      is_recursive: number;
      type: number;
      comment: string | null;
      number_time: number;
      definition_time: string;
      end_of_working_day: number;
      calendars_id: number;
      date_mod: string;
      date_creation: string;
      slms_id: number;
      use_ticket_calendar: number;
    };

    glpi_olas: {
      id: number;
      name: string;
      entities_id: number;
      is_recursive: number;
      type: number;
      comment: string | null;
      number_time: number;
      definition_time: string;
      end_of_working_day: number;
      calendars_id: number;
      date_mod: string;
      date_creation: string;
      slms_id: number;
      use_ticket_calendar: number;
    };

    glpi_slalevels_tickets: {
      id: number;
      tickets_id: number;
      slalevels_id: number;
      date: string;
    };

    glpi_ticketsatisfactions: {
      id: number;
      tickets_id: number;
      type: number;
      date_begin: string | null;
      date_answered: string | null;
      satisfaction: number | null;
      comment: string | null;
    };

    glpi_suppliers: {
      id: number;
      entities_id: number;
      is_recursive: number;
      name: string;
      suppliertypes_id: number;
      registration_number: string | null;
      website: string | null;
      phonenumber: string | null;
      comment: string | null;
      is_active: number;
      date_mod: string;
      date_creation: string;
      fax: string | null;
      email: string | null;
      address: string | null;
      postcode: string | null;
      town: string | null;
      state: string | null;
      country: string | null;
    };

    glpi_suppliers_tickets: {
      id: number;
      tickets_id: number;
      suppliers_id: number;
      type: number;
    };

    glpi_requesttypes: {
      id: number;
      name: string;
      is_helpdesk_default: number;
      is_followup_default: number;
      is_mail_default: number;
      is_mailfollowup_default: number;
      is_ticketcategory_default: number;
      is_ticketsolution_default: number;
      is_active: number;
      comment: string | null;
      date_mod: string;
      date_creation: string;
    };

    glpi_states: {
      id: number;
      name: string;
      entities_id: number;
      is_recursive: number;
      comment: string | null;
      states_id: number;
      completename: string;
      level: number;
      ancestors_cache: string | null;
      sons_cache: string | null;
      is_visible_computer: number;
      is_visible_monitor: number;
      is_visible_networkequipment: number;
      is_visible_peripheral: number;
      is_visible_phone: number;
      is_visible_printer: number;
      is_visible_softwareversion: number;
      is_visible_softwarelicense: number;
      is_visible_line: number;
      is_visible_certificate: number;
      is_visible_rack: number;
      is_visible_passivedcequipment: number;
      is_visible_enclosure: number;
      is_visible_pdu: number;
      is_visible_cluster: number;
      is_visible_contract: number;
      is_visible_appliance: number;
      is_visible_databaseinstance: number;
      date_mod: string;
      date_creation: string;
    };

    glpi_solutiontypes: {
      id: number;
      name: string;
      comment: string | null;
      entities_id: number;
      is_recursive: number;
      date_mod: string;
      date_creation: string;
      inquest_duration: number;
      date_mod: string;
      date_creation: string;
      autofill_decommission_date: string | null;
      suppliers_as_private: number;
      anonymize_support_agents: number;
      contracts_id_default: number;
      display_users_initials: number;
      enable_custom_css: number;
      custom_css_code: string | null;
      latitude: string | null;
      longitude: string | null;
      altitude: string | null;
      calendars_strategy: number;
      changetemplates_strategy: number;
      contracts_strategy_default: number;
      entities_strategy_software: number;
      problemtemplates_strategy: number;
      tickettemplates_strategy: number;
      transfers_strategy: number;
      from_email: string | null;
      from_email_name: string | null;
      noreply_email: string | null;
      noreply_email_name: string | null;
      transfers_id: number;
      agent_base_url: string | null;
    };
  }
}
